install.packages("remotes")
require(remotes)
install_version("optparse", version = "1.7.3", repos = "https://cloud.r-project.org")
install_version("caret", version = "6.0-94", repos = "https://cloud.r-project.org")
install_version("doParallel", version = "1.0.17", repos = "https://cloud.r-project.org")
install_version("benchmarkme", version = "1.0.8", repos = "https://cloud.r-project.org")
install_version("data.table", version = "1.14.8", repos = "https://cloud.r-project.org")
install_version("dplyr", version = "1.1.2", repos = "https://cloud.r-project.org")
install_version("janitor", version = "2.1.0", repos = "https://cloud.r-project.org")
install_version("randomForest", version = "4.7-1.1", repos = "https://cloud.r-project.org")
install_version("gbm", version = "2.1.8.1", repos = "https://cloud.r-project.org")
install_version("ranger", version = "0.15.1", repos = "https://cloud.r-project.org")
install_version("xgboost", version = "1.7.5.1", repos = "https://cloud.r-project.org")
install_version("MLeval", version = "0.3", repos = "https://cloud.r-project.org")
install_version("MLmetrics", version = "1.1.1", repos = "https://cloud.r-project.org")
